version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: parcel-bundler
    versions:
    - 1.12.5
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.17
    - 7.13.10
    - 7.13.9
