language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - lts/*
branches:
  only: source
script:
  - npm run deploy
  - touch dist/.nojekyll
deploy:
  provider: pages
  local-dir: dist
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  fqdn: edm00se.codes
  on:
    branch: master
