name: Upgrade Dependencies

on:
  workflow_dispatch:

jobs:
  upgrade-dependencies:
    uses: edm00se/edm00se/.github/workflows/upgrade-dependencies.yml@master
    secrets: inherit
    with:
      nodever: '20'
